name: Build module

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "module/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "module/**"

jobs:
  build-on-image:
    name: Kernel 5.10
    runs-on: ubuntu-latest
    container:
      image: library/debian:bullseye
      # Disable seccomp until a container manager in GitHub recognizes
      # clone3() syscall,
      # <https://github.com/actions/virtual-environments/issues/3812>.
      options: --security-opt seccomp=unconfined

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install packages required
        run: |
         apt-get update
         apt-get install -y linux-headers-amd64 make g++

      - name: Build kernel module
        run: |
          cd module
          make -Wall -C /lib/modules/5.10*/build M=`pwd`

