name: Build module

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "module/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "module/**"
  # Run every week
  schedule:
    - cron: '0 23 1 * *'

jobs:
  build-on-image:
    name: Kernel ${{ matrix.kversion }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      # Disable seccomp until a container manager in GitHub recognizes
      # clone3() syscall,
      # <https://github.com/actions/virtual-environments/issues/3812>.
      options: --security-opt seccomp=unconfined

    strategy:
      fail-fast: false
      matrix:
        include:
          - kversion: "5.10"
            image: "library/debian:bullseye"
          - kversion: "6.1"
            image: "library/debian:bookworm"
          - kversion: "last stable"
            image: "library/debian:sid"

    steps:
      - uses: actions/checkout@v4

      - name: Install packages required
        run: |
         apt-get update
         apt-get install -y linux-headers-amd64 make g++

      - name: Build kernel module
        run: |
          cd module
          make -Wall -C /lib/modules/*/build M=`pwd`

