name: Test build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "README.md"
      - "doc/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "README.md"
      - "doc/**"
  workflow_dispatch:

jobs:
  build:
    name: amd64
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install packages required
        run: |
         sudo apt-get update
         sudo apt-get install -y g++ cmake uuid-dev libboost-program-options-dev libboost-filesystem-dev libssl-dev

      - name: Build blksnap-dev, blksnap-tools and blksnap-tests
        working-directory: .
        run: |
          cmake .
          make
